In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
df =pd.read_csv(r"C:\Projects\ANN_Project- Customer churn\Churn_Modelling.csv")

In [3]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.2 MB

In [5]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [6]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
#preprocess the data
df1 = df.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [8]:
df1

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
# the gender and contry are categorical features so we cna encode it using label encoder
# since gender has only M or F we cna use Label encoder(usually for target variables(y))
 # but since its only 2 cat we cna use LE here
# But for Geography we have multiple countries, so LE cannot be sued here.
# like for most Feature columns we use OHE, so we use OHE for Geography feature

In [10]:
le_gender= LabelEncoder()
df1['Gender'] = le_gender.fit_transform(df['Gender'])
df1

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [11]:
# Encoding Geography using OHE
from sklearn.preprocessing import OneHotEncoder

In [12]:
ohe = OneHotEncoder()

# Use double brackets to keep it 2D
geo_encoded = ohe.fit_transform(df1[['Geography']])
geo_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [42]:
ohe.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [14]:
geo_df = pd.DataFrame(geo_encoded.toarray(), columns=ohe.get_feature_names_out(['Geography']))

In [41]:
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [16]:
# Updateing this with the new df

# deleting geo col cos we have ctreated new cols instead of that one using OHE

df1 = df1.drop('Geography',axis=1)

In [17]:
df1.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,42,2,0.00,1,1,1,101348.88,1
1,608,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,39,1,0.00,2,0,0,93826.63,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0

In [18]:
#now we need to conbine the New cat geographical feature columns to the og DF1

df1 = pd.concat([df1,geo_df],axis=1)

In [19]:
df1.head()
#can see the new colmns added

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [20]:
## we need to save eveything we did into pickle file
with open('le_gender.pkl','wb') as file:
    pickle.dump(le_gender,file)

with open('ohe.pkl','wb') as file:
    pickle.dump(ohe,file)

In [21]:
### divinding the Data into  Independent ad dependetn features X and Y

X = df1.drop(['Exited'],axis=1)
y= df1['Exited']

In [22]:
#Train test split it

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state =42)

In [23]:
# Now we will scale the features

scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#scaling is only done on features data

In [24]:
# save this as pkl as well

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

ANN IMPLEMENTATION

In [25]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

WARNING:tensorflow:From c:\Projects\ANN_Project- Customer churn\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [26]:
# Building the ANN model

model = Sequential(
    [
Dense(64, activation='relu', input_shape=(X_train.shape[1],)), # HL1 connected to the input layer   
Dense(32, activation='relu'), #HL2 connected to HL1
Dense(1, activation='sigmoid') #output layer connected to HL2
    ]
)

WARNING:tensorflow:From c:\Projects\ANN_Project- Customer churn\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
# we can see the number of parameters in each layer and the total number of parameters
#  in the model above

In [29]:
# complile the model
import tensorflow

opt = tensorflow.keras.optimizers.Adam(learning_rate=0.001) # here we can fix our own learning rate but above it's fixed for adam
loss =tensorflow.keras.losses.BinaryCrossentropy() # here we can fix our own loss function but above it's fixed for binary classification

In [30]:
#or
#model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [31]:
## setup early stopping and tensorboard callbacks
#whats early stopping and tensorboard callbacks?
#its a technique to stop the training of the model when the validation loss starts to
# increase, which helps to prevent overfitting.
# TensorBoard is a visualization tool that allows us to monitor the training process and 
# visualize metrics such as loss and accuracy over time.

In [32]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard


# tensorboard 
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S") # this will create a new log directory with the current date and time, which helps to organize the logs for different training runs.
tensorflow_callbacks =  TensorBoard(log_dir=log_dir, histogram_freq=1) # this will log the training metrics to the specified log directory, and histogram_freq=1 means that it will log histograms of weights and biases every epoch.

In [33]:
# early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True) 
# this will monitor the validation loss and stop training if it doesn't improve for 5 consecutive epochs, and restore the best weights.

In [34]:
## Train the model
history = model.fit(
    X_train, y_train, validation_data=(X_test, y_test), epochs=100,
     callbacks=[early_stopping,tensorflow_callbacks]
     )

Epoch 1/100
WARNING:tensorflow:From c:\Projects\ANN_Project- Customer churn\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Projects\ANN_Project- Customer churn\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 8s 12ms/step - loss: 0.4505 - accuracy: 0.8051 - val_loss: 0.4023 - val_accuracy: 0.8355
Epoch 2/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3904 - accuracy: 0.8421 - val_loss: 0.3615 - val_accuracy: 0.8495
Epoch 3/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3573 - accuracy: 0.8561 - val_loss: 0.3495 - val_accuracy: 0.8605
Epoch 4/100
250/250 [==============================] - 3s 13ms/step - loss: 0.3467 - accuracy: 0.8561 - val_loss: 0.3481 - val_accuracy: 0.8615
Epoch 5/100
250/250 [==============================] - 3s 13ms/step - loss: 0.3408 - accuracy: 0.8605 - val_loss: 0.3473 - val_accuracy: 0.8580
Epoch 6/100
250/250 [==============================] - 3s 14ms/step - loss: 0.3374 - accuracy: 0.8615 - val_loss: 0.3474 - val_accuracy: 0.8605
Epoch 7/100
250/250 [==============================] - 4s 14ms/step - loss: 0.3334 - accuracy: 0.8610 - val_loss: 0.3473 - val_accuracy: 0.8595
Epoch 8/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3321 - accuracy: 0.8631 - val_loss: 0.3433 - val_accuracy: 0.8615
Epoch 9/100
250/250 [==============================] - 2s 10ms/step - loss: 0.3284 - accuracy: 0.8633 - val_loss: 0.3464 - val_accuracy: 0.8650
Epoch 10/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3267 - accuracy: 0.8636 - val_loss: 0.3505 - val_accuracy: 0.8605
Epoch 11/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3251 - accuracy: 0.8658 - val_loss: 0.3485 - val_accuracy: 0.8600
Epoch 12/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3251 - accuracy: 0.8661 - val_loss: 0.3447 - val_accuracy: 0.8590
Epoch 13/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3223 - accuracy: 0.8656 - val_loss: 0.3475 - val_accuracy: 0.8590

In [35]:
# we cna asee abve that the model is trained for 20 epochs and then 
# it stopped because of early stopping, and we can also see the training and
#  validation loss and accuracy for each epoch.
# it stops when the loss stops decreasing for 5 consecutive epochs, which is the patience we set in early stopping.
# if you wanna check for more, you cna increase the patience in early stopping(to 10) or remove it to see all epochs.

In [36]:
# now we need to save the model as h5 instead of pkl because its compatible with keras model
model.save('model.h5')

c:\Projects\ANN_Project- Customer churn\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [43]:
## lets load the tensorboard to visualize the training process
%reload_ext tensorboard

In [44]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 16324), started 12:16:35 ago. (Use '!kill 16324' to kill it.)

In [39]:
# why did it fail?
#because we are running this in vscode and tensorboard is not supported in vscode, so we need to run this in jupyter notebook or colab to visualize the tensorboard.

In [ ]:
## now for prediction we need to load the pickle files and the model
# so chck out the predcition ipynb file for that.